services:
  spark-master:
    image: spark-image
    container_name: spark-master
    ports:
      - "8080:8080"
    environment:
      - SPARK_MODE=master
  spark-worker-1:
    image: spark-image
    container_name: spark-worker-1
    ports:
      - "8082:8081"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
  spark-worker-2:
    image: spark-image
    container_name: spark-worker-2
    ports:
      - "8083:8081"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
  spark-worker-3:
    image: spark-image
    container_name: spark-worker-3
    ports:
      - "8084:8081"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077